---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kibana-proxy
  name: kibana-proxy
  namespace: monitoring
spec:
  type: ExternalName
  externalName: vpc-opensearch-stage-mon-fhdhhs2ktec5zddpepkno2ereu.us-west-2.es.amazonaws.com
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: htpasswd
    nginx.ingress.kubernetes.io/auth-realm: 'You may ask yourself: How did I get here?'
  name: kibana-proxy
  namespace: monitoring
spec:
  tls:
  - hosts:
    - kibana.k8s.castlerock.ai
    secretName: kibana-tls-cert
  rules:
    - host: kibana.k8s.castlerock.ai
      http:
        paths:
          - path: "/" 
            pathType: Prefix
            backend:
             service:
              name: kibana-proxy
              port:
                number: 80
